export const ROUTES = {
  home: "/",
  menu: "/menu",
  dish: (id: string) => `/dish/${id}`,
  cart: "/basket",
  checkout: "/checkout",
  orders: "/orders",
  orderDetail: (id: string) => `/order/${id}`,
  track: (id: string) => `/track/${id}`,
  wellness: "/wellness",
  subscriptions: "/subscriptions",
  consultRD: "/consult-rd",
  healthQuiz: "/health-quiz",
  gold: "/gold",
  profile: "/profile",
  settings: "/settings",
  notifications: "/notifications",
  support: "/support",
  // Admin / Ops
  admin: "/admin",
  kds: "/admin/kds",
  staff: "/admin/staff",
  riders: "/admin/riders",
  analytics: "/admin/analytics",
} as const;
